units:
  ks: 15
  kc: 18.5
  kp: kc + 1
  ep: 6
  screw_size: 1.5
points:
  key:
    height: kc
    width: kc
    spread: kp
    padding: kp
  zones:
    matrix:
      anchor:
        rotate: 8
        shift: [50, -150]
      columns:
        outer:
          key.splay: 2
          key.column_net: P15
        pinky:
          key.stagger: 2
          key.column_net: P14
        ring:
          key.stagger: 4
          key.splay: -2
          key.column_net: P16
        middle:
          key.stagger: 3
          key.column_net: P10
        index:
          key.splay: -4
          key.stagger: -3
          rows.mod.skip: true
          key.column_net: P20
        inner:
          key.splay: -4
          key.stagger: -3
          rows.mod.skip: true
          key.column_net: P19
      rows:
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -1kp - 10]
        rotate: -20
      columns:
        inner:
          key.column_net: P20
        home:
          key.height: 1.5kc
          key.shift: [0, 0.25kc]
          key.rotate: -90
          key.column_net: P19
        outer:
          key.height: 1.5kc
          key.shift: [0, 0.25kc]
          key.rotate: -90
          key.column_net: P18
      rows:
        cluster:
          row_net: P9
outlines:
  switches:
    - what: rectangle
      where: true
      size: [ks, ks]
  keycaps:
    - what: rectangle
      where: true
      size: [kc, kc]
  board:
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_outer_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_pinky_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_pinky_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_ring_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_ring_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_middle_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_middle_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_index_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_index_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_inner_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_inner_top
          shift: [2kc - (ep / 2), 0.5kc]
        - ref: matrix_inner_bottom
          shift: [2kc - (ep / 2), -0.75kc]
        - ref: thumbfan_outer_cluster
          shift: [-0.75kc, 0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [0.75kc, 0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [0.75kc, -3kc]
        - ref: matrix_outer_mod
          shift: [-0.5kc, -0.5kc]
      expand: ep
      joints: round
  holes:
    top_left:
      what: circle
      radius: screw_size
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_middle:
      what: circle
      radius: screw_size
      where:
        - ref: matrix_middle_top
          shift: [0, 0.5kc + 2]
    top_right:
      what: circle
      radius: screw_size
      where:
        - ref: matrix_inner_top
          shift: [2kc - (ep / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: screw_size
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (ep / 2) + 1, -0.5kc - (ep / 2) - 1]
    bottom_right:
      what: circle
      radius: screw_size
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: screw_size
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: screw_size
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]
  drilled_board:
    - name: board
    - operation: subtract
      name: holes
pcbs:
  janus:
    outlines:
      main:
        outline: drilled_board
    footprints:
      ks27:
        what: ks27
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [9, 6]
          rotate: -90
      rev_nano:
        what: rev_nano
        where:
          ref: matrix_inner_top
          shift: [1kc + 3, -2]
      rev_view:
        what: niceview
        params:
          side: "F"
          reverse: true
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref: matrix_inner_top
          shift: [1kc + 3, -6]
      rev_jstph:
        what: rev_jstph
        params:
          pos: BPOS
          neg: GND
        where:
          ref: matrix_inner_home
          shift: [2kc - 3, -5]
          rotate: 180
      rev_slider:
        what: rev_slider
        params:
          from: BPOS
          to: RAW
        where:
          ref: matrix_inner_bottom
          shift: [2kc + 1, 0]
          rotate: -90
      rev_reset:
        what: rev_button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_bottom
          shift: [1kc + 3, 0]
          rotate: -90
