units:
  ks: 15 # KS-27 switch size
  kc: 18.2 # DSA keycap size
  kp: kc + 1 # Padding so keycaps don't touch
  board_padding: 6
  screw_radius: 1.15 # M2 screws are ~1.8mm, spec is 2mm
  insert_radius: 1.55 # Brass threaded insert radius is ~3.48mm, this radius should be snug
  insert_wall_radius: insert_radius + 2.5 # This is the plastic AROUND the threaded inserts
  insert_print_clearance: 0.1
  case_clearance: 0.3
points:
  key:
    height: kc
    width: kc
    spread: kp
    padding: kp
  zones:
    matrix:
      anchor:
        rotate: 0
        shift: [50, -150] # For Kicad - this puts it closer to the center
      columns:
        outer:
        pinky:
          key.stagger: 2
        ring:
          key.spread: kp + 1
          key.splay: -4
          key.stagger: 6
        middle:
          key.stagger: 3
          rows.mod.skip: true
        index:
          key.splay: -4
          key.stagger: -3
          rows.mod.skip: true
        inner:
          key.stagger: -3
          rows.mod.skip: true
      rows:
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
        number:
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1kc - 6]
        rotate: -6
      columns:
        mod:
        inner:
          key.splay: -8
          key.shift: [2, -1]
          key.column_net: P20
          key.rotate: -90 # Rotated counter-clockwise to make routing easier
        home:
          key.splay: -8
          key.height: 1.5kc # I'm  aware that this looks wrong in ergogen because of the rotate
          key.shift: [4, 0.25kc - 2]
          key.rotate: 0
          key.column_net: P19
        outer:
          key.splay: -8
          key.height: 1.5kc # I'm  aware that this looks wrong in ergogen because of the rotate
          key.shift: [6, 0.25kc - 3]
          key.rotate: 0
          key.column_net: P18
      rows:
        cluster:
          row_net: P9
outlines:
  switches: # Just to help me see in the web viewer
    - what: rectangle
      where: true
      size: [ks, ks]
  keycaps: # Just to help me see in the web viewer
    - what: rectangle
      where: true
      size: [kc, kc]

  board: # Defining the board outline and adding the padding (6mm)
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_outer_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_pinky_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_pinky_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_ring_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_ring_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_middle_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_middle_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_index_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_index_top
          shift: [0.5kc, 0.5kc]
        - ref: matrix_inner_top
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2), 0.5kc]
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2), -0.75kc]
        - ref: thumbfan_outer_cluster
          shift: [-0.75kc, 0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [0.75kc, 0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [0.75kc, -3kc]
        - ref: matrix_outer_mod
          shift: [-0.5kc, -0.5kc]
      expand: board_padding
      joints: round # Makes it look nice
  # --------------------------------------------------------
  # Files with "_" prefix don't generate output.
  #
  # _board_case_clearance - this is the PCB outline + 1.5mm,
  # otherwise the PCB ends up very snug in the case.
  #
  # _board_xl - this is the outer wall of the case.
  # --------------------------------------------------------
  _board_case_clearance:
    - what: outline
      name: board
      expand: case_clearance
  _board_xl:
    - what: outline
      name: _board_case_clearance
      expand: 2

  _board_holes: # Holes for screws to go through PCB
    top_left:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_middle:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_middle_top
          shift: [0, 0.5kc + 2]
    top_right:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 1, -0.5kc - (board_padding / 2) - 1]
    bottom_right:
      what: circle
      radius: screw_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: screw_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _insert_holes: # Holes for threaded inserts to go in
    top_left:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_middle:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_middle_top
          shift: [0, 0.5kc + 2]
    top_right:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 1, -0.5kc - (board_padding / 2) - 1]
    bottom_right:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _insert_walls: # The walls to go AROUND the threaded inserts
    top_left:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_middle:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_middle_top
          shift: [0, 0.5kc + 2]
    top_right:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 1, -0.5kc - (board_padding / 2) - 1]
    bottom_right:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _slider_hole:
    - what: rectangle
      size: [2, 8]
      where:
        - ref: matrix_inner_bottom
          shift: [2kc + 4 + case_clearance, 0]

  inserts: # Make a big circle, subtract little circle = standoffs
    - name: _insert_walls
    - operation: subtract
      name: _insert_holes

  wall: # Make big board outline, subtract normal board outline = a case wall
    - name: _board_xl
    - operation: subtract
      name: _board_case_clearance

  drilled_board: # Drill the M2 screw holes in the board
    - name: board
    - operation: subtract
      name: _board_holes
