units:
  ks: 15 # KS-27 switch size (roughly)
  ks_w: 14.45 # ACTUAL KS-27 width for keyplate
  ks_h: 13.95 # ACTUAL KS-27 height for keyplate
  kc: 18.2 # DSA keycap size
  kp: kc + 1 # Padding so keycaps don't touch
  board_padding: 6
  screw_radius: 1.15 # M2 screws are ~1.8mm, spec is 2mm
  insert_radius: 1.55 # Brass threaded insert radius is ~3.48mm, this radius should be snug
  insert_wall_radius: insert_radius + 2.5 # This is the plastic AROUND the threaded inserts
  insert_print_clearance: 0.1
  case_clearance: 0.3
points:
  key:
    height: kc
    width: kc
    spread: kp
    padding: kp
  zones:
    matrix:
      anchor:
        rotate: 0
        shift: [50, -150] # For Kicad - this puts it closer to the center
      columns:
        outer:
          key.column_net: P15
        pinky:
          key.column_net: P14
        ring:
          key.splay: -2
          key.spread: kp + 0.2
          key.stagger: -0.35
          key.column_net: P16
        middle:
          rows.mod.skip: true
          key.column_net: P10
        index:
          key.splay: -2
          key.spread: kp + 0.2
          key.stagger: -0.35
          rows.mod.skip: true
          key.column_net: P19
        inner:
          rows.mod.skip: true
          key.column_net: P20
      rows:
        mod:
          row_net: P9
        bottom:
          row_net: P8
        home:
          row_net: P7
        top:
          row_net: P6
        number:
          row_net: P5
    thumbfan:
      anchor:
        ref: matrix_index_bottom
        shift: [0, -1kc - 6]
        rotate: -6
      columns:
        mod:
          key.rotate: -90
          key.column_net: P10
        inner:
          key.splay: -8
          key.shift: [2, -1]
          key.rotate: -90
          key.column_net: P19
        home:
          key.splay: -8
          key.width: 1.5kc
          key.shift: [4, 0.25kc - 2]
          key.rotate: -90
          key.column_net: P20
        outer:
          key.splay: -8
          key.width: 1.5kc
          key.shift: [6, 0.25kc - 3]
          key.rotate: -90
          key.column_net: P18
      rows:
        cluster:
          row_net: P9
outlines:
  switches: # Just to help me see in the web viewer
    - what: rectangle
      where: true
      size: [ks_w, ks_h]
  keycaps: # Just to help me see in the web viewer
    - what: rectangle
      where: true
      size: [kc, kc]

  board: # Defining the board outline and adding the padding (6mm)
    - what: polygon
      operation: stack
      points:
        - ref: matrix_outer_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_outer_number
          shift: [0.5kc, 0.5kc]
        - ref: matrix_pinky_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_pinky_number
          shift: [0.5kc, 0.5kc]
        - ref: matrix_ring_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_ring_number
          shift: [0.5kc, 0.5kc]
        - ref: matrix_middle_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_middle_number
          shift: [0.5kc, 0.5kc]
        - ref: matrix_index_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_index_number
          shift: [0.5kc, 0.5kc]
        - ref: matrix_inner_number
          shift: [-0.5kc, 0.5kc]
        - ref: matrix_inner_number
          shift: [2kc - (board_padding / 2), 0.5kc]
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2), -0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [-0.75kc, -0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [-0.75kc, 0.5kc]
        - ref: thumbfan_outer_cluster
          shift: [0.75kc, 0.5kc]
        - ref: thumbfan_home_cluster
          shift: [0.75kc, 0.5kc]
        - ref: thumbfan_inner_cluster
          shift: [0.5kc, 0.5kc]
        - ref: thumbfan_inner_cluster
          shift: [0.5kc, -0.5kc]
        - ref: thumbfan_mod_cluster
          shift: [0.5kc, -0.5kc]
        - ref: matrix_outer_mod
          shift: [-0.5kc, -0.5kc]
      expand: board_padding
      joints: round # Makes it look nice
  # --------------------------------------------------------
  # Files with "_" prefix don't generate output.
  #
  # _board_case_clearance - this is the PCB outline + 1.5mm,
  # otherwise the PCB ends up very snug in the case.
  #
  # _board_xl - this is the outer wall of the case.
  # --------------------------------------------------------
  _board_case_clearance:
    - what: outline
      name: board
      expand: case_clearance
  _board_xl:
    - what: outline
      name: _board_case_clearance
      expand: 2

  _board_holes: # Holes for screws to go through PCB
    top_left:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_outer_number
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_right:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_inner_number
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 5, -0.5kc - (board_padding / 2) - 4]
    bottom_right:
      what: circle
      radius: screw_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: screw_radius
      where:
        - ref: thumbfan_mod_cluster
          shift: [0.5kc + 1, -0.5kc - 1]
    bottom_left:
      what: circle
      radius: screw_radius
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _insert_holes: # Holes for threaded inserts to go in
    top_left:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_right:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 1, -0.5kc - (board_padding / 2) - 1]
    bottom_right:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: insert_radius + insert_print_clearance
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _insert_walls: # The walls to go AROUND the threaded inserts
    top_left:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_outer_top
          shift: [-0.5kc - 1, 0.5kc + 1]
    top_right:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_inner_top
          shift: [2kc - (board_padding / 2) + 1, 0.5kc + 1]
    right_middle:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_inner_bottom
          shift: [2kc - (board_padding / 2) + 1, -0.5kc - (board_padding / 2) - 1]
    bottom_right:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, 0.5kc + 1]
    bottom_middle:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: thumbfan_outer_cluster
          shift: [0.75kc + 1, -3kc - 1]
    bottom_left:
      what: circle
      radius: insert_wall_radius
      where:
        - ref: matrix_outer_mod
          shift: [-0.5kc - 1, -0.5kc - 1]

  _slider_hole:
    - what: rectangle
      size: [2, 8]
      where:
        - ref: matrix_inner_bottom
          shift: [2kc + 4 + case_clearance, 0]

  _supports:
    left:
      what: circle
      radius: 2
      where:
        ref: matrix_pinky_home
        shift: [-2, 0.5kc + 0.6]
    middle:
      what: circle
      radius: 2
      where:
        ref: matrix_middle_home
        shift: [-2, 0.5kc + 0.6]
    right:
      what: circle
      radius: 2
      where:
        ref: matrix_inner_home
        shift: [-2, 0.5kc + 0.6]

  keyplate:
    - name: _board_case_clearance
    - operation: subtract
      name: switches
  keyplate_drilled:
    - name: keyplate
    - operation: subtract
      name: _board_holes

  inserts: # Make a big circle, subtract little circle = standoffs
    - name: _insert_walls
    - operation: subtract
      name: _insert_holes

  wall: # Make big board outline, subtract normal board outline = a case wall
    - name: _board_xl
    - operation: subtract
      name: _board_case_clearance

  drilled_board: # Drill the M2 screw holes in the board
    - name: board
    - operation: subtract
      name: _board_holes

pcbs:
  janus:
    outlines:
      main:
        outline: drilled_board
    footprints:
      ks27:
        what: ks27
        where: true
        params:
          keycaps: true # Adds keycap reference in KiCad (User.Dwgs layer)
          hotswap: true # Adds pads and holes for hotswap socket
          reverse: true # Adds pads and holes on both sides so you can make a reversible PCB
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode: # Need these since we don't have enough pins for 25 keys
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [9, 6]
          rotate: -90
      rev_nano: # This allows you to use the same thru-holes on either side of the board for the nice!nano v2
        what: rev_nano
        where:
          ref: matrix_inner_number
          shift: [1kc + 3, -2]
      rev_view: # Like above, lets you use the nice!vier on either side of the board
        what: niceview
        params:
          side: "F"
          reverse: true
          MOSI: P2
          SCK: P3
          CS: P1
        where:
          ref: matrix_inner_number
          shift: [1kc + 3, -6]
      rev_jstph: # Mainly just adds silk screen to both sides of the board to ensure proper polarity
        what: rev_jstph
        params:
          pos: BPOS
          neg: GND
        where:
          ref: matrix_inner_top
          shift: [2kc - 3, -5]
          rotate: 180
      rev_slider: # Adds a power slider to both sides of the board
        what: rev_slider
        params:
          from: BPOS
          to: RAW
        where:
          ref: matrix_inner_home
          shift: [2kc + 1, 0]
          rotate: -90
      rev_reset: # Adds a reset button to both sides of the board
        what: rev_button
        params:
          from: GND
          to: RST
        where:
          ref: matrix_inner_home
          shift: [1kc + 3, 0]
          rotate: -90

cases:
  _case_wall:
    - name: wall
      extrude: 5
  _case_keyplate:
    - name: keyplate
      extrude: 1
  # --------------------------------------------------------
  #
  # This "key_tester" is basically a keyplate with a wall.
  # I will print it as is, then flip it upside down and
  # put switches with keycaps into the keyplate to get a
  # feel for whether or not I like the layout.
  #
  # --------------------------------------------------------
  key_tester:
    - what: case
      name: _case_wall
      operation: add
    - what: case
      name: _case_keyplate
      operation: add
